version: '3'
services:
  producer:
    build: ./producer
    volumes:
      - ./producer:/srv/producer
    command: python3 -u /srv/producer/run.py
    container_name: producer
    working_dir: /srv/producer
    depends_on:
      - redis
    networks:
      - redis-net

  consumer:
    build: ./consumer
    volumes:
      - ./consumer:/srv/consumer
    command: python3 -u /srv/consumer/run.py
    container_name: consumer
    working_dir: /srv/consumer
    depends_on:
      - redis
    networks:
      - redis-net

  redis:
    container_name: redis
    image: redis
    ports:
      - "6379:6379"
    volumes:
      - ../data/redis:/data
    restart: always
    networks:
      - redis-net

networks:
  redis-net:
